version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
       - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  wordpress:
    depends_on: 
      - db
    build: ./docker/wordpress
    ports:
      - 8080:80
    restart: always
    volumes:
      - app_data:/var/www/html
      # - ./src/my-plugin:/var/www/html/wp-content/plugins/my-plugin:cached
    env_file:
      - .env

volumes:
  db_data:
  app_data: