version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
       - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  wordpress:
    depends_on: 
      - db
    build: ./docker/wordpress
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file:
      - .env

  sass:
    build: ./docker/sass
    restart: on-failure
    environment:
      WATCH: 1
    volumes:
      - ./web/wp-content/themes/twentyseventeen/assets/sass:/sass
      - ./web/wp-content/themes/twentyseventeen/assets/css:/css

volumes:
  db_data: